version: "3.9"
services:
  postgres:
    image: postgresql
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=users
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgresql
      - DB_PORT=5432
