# Default values for your-helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "your-docker-repo/your-image-name"
  pullPolicy: IfNotPresent
  tag: "latest"

migration:
  image:
    hostname: "docker.io"
    repository: "/golang-enthusiast/k8-golang-demo-data-migration"
    tag: "0.3.0"
    pullPolicy: IfNotPresent 

service:
  type: ClusterIP
  port: 8080
  httpPort: 8080
  name: rest

postgres:
  enabled: true
  host: "your-postgres-service-name"
  postgresDatabase: "users"
  postgresUser: "root"
  postgresPassword: "qwerty"
  service:
    port: 5432

ingress:
  name: http
  protocol: HTTP
  port: 80
  extension: svc.cluster.local
  enabled: true
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix

skaffold: false

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
