apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "k8-golang-demo.fullname" . }}-data-migration-job
  namespace: {{ .Release.Namespace }}
  labels: {{ include "k8-golang-demo.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "k8-golang-demo.name" . }}-migration
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
    spec:
      restartPolicy: Never
      initContainers:
        - name: init-data-migration
          image: busybox
          command: ['sh', '-c', "until nc -w 2 {{ .Release.Name }}-postgres-1 {{ .Values.postgres.service.port }}; do echo Waiting for {{ .Release.Name }}-postgres-1; sleep 2; done;"]
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.migration.image.hostname }}{{ .Values.migration.image.repository }}:{{ .Values.migration.image.tag }}"
          imagePullPolicy: {{ .Values.migration.image.pullPolicy }}
          env:
            - name: DATABASE_HOST
              value: "{{ .Release.Name }}-postgres-1" 
            - name: DATABASE_PORT
              value: "{{ .Values.postgres.service.port | quote }}"
            - name: DATABASE_NAME
              value: "{{ .Values.postgres.postgresDatabase | quote }}"
            - name: DATABASE_USER
              value: "{{ .Values.postgres.postgresUser | quote }}"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "k8-golang-demo.fullname" . }}-secrets
                  key: postgresPassword
            - name: DATABASE_DRIVER
              value: "{{ .Values.postgres.postgresDriver | quote }}"
